# Generated by Django 5.0.2 on 2024-03-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newuser',
            managers=[
            ],
        ),
    ]
