# Generated by Django 4.1.5 on 2023-01-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('catch', models.CharField(max_length=10)),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('image', models.ImageField(height_field='height', upload_to='static/APP/', width_field='width')),
                ('details', models.TextField()),
            ],
        ),
    ]
