# Generated by Django 4.1.5 on 2023-01-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP2', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='height',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='width',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='static/APP/'),
        ),
    ]
