# Generated by Django 4.1.5 on 2023-02-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP2', '0004_remove_blog_height_remove_blog_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='BLOG/media/'),
        ),
    ]
