# Generated by Django 4.1.5 on 2023-02-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP2', '0014_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='catch',
            field=models.CharField(default='CATCH', max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='TITLE', max_length=10),
        ),
    ]
