# Generated by Django 4.1.5 on 2023-02-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP2', '0015_alter_blog_catch_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
