# Generated by Django 4.1.5 on 2023-02-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP2', '0017_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
