# Generated by Django 4.1.5 on 2023-02-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP2', '0020_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
