# Generated by Django 4.1.5 on 2023-02-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP2', '0022_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
