# Generated by Django 5.0.2 on 2024-03-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecreatemodel',
            name='thumbnail',
            field=models.ImageField(upload_to='static/thumbs/'),
        ),
    ]
