# Generated by Django 5.0.2 on 2024-03-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleviewmodel',
            name='btitle',
            field=models.CharField(),
        ),
    ]
