# Generated by Django 5.0.2 on 2024-03-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleviewmodel',
            name='per_like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
