# Generated by Django 5.0.2 on 2024-03-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_articleviewmodel_per_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleviewmodel',
            name='per_like',
        ),
    ]
