# Generated by Django 5.0.2 on 2024-03-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_articlecreatemodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecreatemodel',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbs/'),
        ),
    ]
