# Generated by Django 5.0.2 on 2024-03-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_articlecreatemodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecreatemodel',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
